### ISSUE TITLE
Terms for Events

### ISSUE THREAD

**Issue by sebastiankb** [iot-schema-collab/iotschema#4]
In the TD spec we have a simple example ( [see Example 1](https://w3c.github.io/wot-thing-description/#introduction)) that defines an Event "overheating". I would like to annotated it with, e.g., "Warning" , "Alarm", and/or "temperatureExceed". Would be great to have something to select.

**Comment by mjkoster** [comment]
In iotschema we should be able to define enumerations using data constraints.  This could be a good thing to add sooner rather than later.

**Comment by danicic** [comment]
@sebastiankb: thanks. We have added Events for all writable Properties, including [TargetTemperatureChanged and others](https://github.com/iot-schema-collab/iotschema/blob/master/property-events.jsonld).
